import type { ModelPack } from '../types.js';

export const slotwirePack: ModelPack = {
  name: '@slottd/pack-slotwire',
  author: '@slottd',
  version: '1.0.0',
  collections: {
    pages: {
      name: 'pages',
      displayName: 'Content Pages',
      icon: '📄',
      description: 'Master page containers (About, Philosophy, Legal, Custom narratives)',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Page Title / Heading', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'URL Slug', required: true },
        { name: 'badgeText', type: 'TEXT', widget: 'text', label: 'Badge Label' },
        { name: 'subtitle', type: 'TEXT', widget: 'textarea', label: 'Page Subtitle' },
        { name: 'description', type: 'TEXT', widget: 'textarea', label: 'Meta Description (SEO)' },
        { name: 'content', type: 'TEXT', widget: 'markdown', label: 'Body Content (Markdown)', required: true },
        { name: 'heroImage', type: 'TEXT', widget: 'media', label: 'Banner / Profile Image' },
        { name: 'founderName', type: 'TEXT', widget: 'text', label: 'Founder Name' },
        { name: 'founderRole', type: 'TEXT', widget: 'text', label: 'Founder Role' },
        { name: 'founderLocation', type: 'TEXT', widget: 'text', label: 'Founder Location' },
        { name: 'founderHandle', type: 'TEXT', widget: 'text', label: 'Founder Handle' },
        { name: 'careerHighlights', type: 'TEXT', widget: 'markdown', label: 'Career Journey / Highlights' },
      ],
    },
    page_sections: {
      name: 'page_sections',
      displayName: 'Page Sections',
      icon: '🧱',
      description: 'Universal layout slots mapped by composite identity (pageSlug + sectionKey)',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Section Title', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Slug', required: true },
        { name: 'pageSlug', type: 'TEXT', widget: 'text', label: 'Parent Page Slug', required: true },
        { name: 'sectionKey', type: 'TEXT', widget: 'text', label: 'Section Key (e.g. hero, projects, services)', required: true },
        { name: 'badgeText', type: 'TEXT', widget: 'text', label: 'Badge Label' },
        { name: 'badgeIcon', type: 'TEXT', widget: 'text', label: 'Badge Icon' },
        { name: 'description', type: 'TEXT', widget: 'textarea', label: 'Description' },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
        { name: 'enabled', type: 'BOOLEAN', widget: 'boolean', label: 'Enabled', defaultValue: true },
        { name: 'primaryCtaText', type: 'TEXT', widget: 'text', label: 'Primary CTA Text' },
        { name: 'primaryCtaUrl', type: 'TEXT', widget: 'text', label: 'Primary CTA URL' },
        { name: 'secondaryCtaText', type: 'TEXT', widget: 'text', label: 'Secondary CTA Text' },
        { name: 'secondaryCtaUrl', type: 'TEXT', widget: 'text', label: 'Secondary CTA URL' },
      ],
    },
    feature_cards: {
      name: 'feature_cards',
      displayName: 'Feature Cards',
      icon: '🎴',
      description: 'Multi-column grids and bento tiles',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Card Title', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Card Slug', required: true },
        { name: 'pageSlug', type: 'TEXT', widget: 'text', label: 'Page Slug', required: true },
        { name: 'sectionKey', type: 'TEXT', widget: 'text', label: 'Section Key', required: true },
        { name: 'badgeText', type: 'TEXT', widget: 'text', label: 'Badge Label' },
        { name: 'icon', type: 'TEXT', widget: 'text', label: 'Card Icon' },
        { name: 'summary', type: 'TEXT', widget: 'textarea', label: 'Short Summary' },
        { name: 'content', type: 'TEXT', widget: 'markdown', label: 'Detailed Content' },
        { name: 'colSpan', type: 'INTEGER', widget: 'number', label: 'Column Span (1 or 2)', defaultValue: 1 },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
        { name: 'linkUrl', type: 'TEXT', widget: 'text', label: 'Link URL' },
        { name: 'linkText', type: 'TEXT', widget: 'text', label: 'Link Text' },
      ],
    },
    gallery: {
      name: 'gallery',
      displayName: 'Media Gallery',
      icon: '🖼️',
      description: 'Universal media arrays and visual showcases',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Title', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Slug', required: true },
        { name: 'galleryKey', type: 'TEXT', widget: 'text', label: 'Gallery Key (e.g. pottery, hardware)', required: true },
        { name: 'pageSlug', type: 'TEXT', widget: 'text', label: 'Page Slug' },
        { name: 'alt', type: 'TEXT', widget: 'text', label: 'Image Alt Text', required: true },
        { name: 'imageUrl', type: 'TEXT', widget: 'media', label: 'Image Asset (R2)', required: true },
        { name: 'caption', type: 'TEXT', widget: 'textarea', label: 'Caption' },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
      ],
    },
    endorsements: {
      name: 'endorsements',
      displayName: 'Endorsements & Social Proof',
      icon: '💬',
      description: 'Client reviews, partner recommendations, and press quotes',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Headline / Summary' },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Slug' },
        { name: 'kind', type: 'TEXT', widget: 'select', label: 'Endorsement Kind', options: [
          { label: 'Partner Endorsement', value: 'partner_endorsement' },
          { label: 'Client Review', value: 'client_review' },
          { label: 'Press Quote', value: 'press_quote' },
          { label: 'Award', value: 'award' },
        ] },
        { name: 'authorName', type: 'TEXT', widget: 'text', label: 'Author Name' },
        { name: 'authorRole', type: 'TEXT', widget: 'text', label: 'Author Role / Title' },
        { name: 'companyOrOrg', type: 'TEXT', widget: 'text', label: 'Company / Organization' },
        { name: 'authorUrl', type: 'TEXT', widget: 'text', label: 'Author / Company URL' },
        { name: 'quoteText', type: 'TEXT', widget: 'textarea', label: 'Quote Narrative', required: true },
        { name: 'avatarUrl', type: 'TEXT', widget: 'media', label: 'Avatar / Photo (R2)' },
        { name: 'rating', type: 'INTEGER', widget: 'number', label: 'Star Rating (1-5)' },
        { name: 'featured', type: 'BOOLEAN', widget: 'boolean', label: 'Featured', defaultValue: false },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
      ],
    },
    qa_items: {
      name: 'qa_items',
      displayName: 'Q&A and FAQs',
      icon: '❓',
      description: 'Structured question and answer pairs for accordions and Schema.org FAQ SEO',
      schemaVersion: 1,
      fields: [
        { name: 'question', type: 'TEXT', widget: 'text', label: 'Question', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Slug', required: true },
        { name: 'answer', type: 'TEXT', widget: 'markdown', label: 'Answer Content (Markdown)', required: true },
        { name: 'category', type: 'TEXT', widget: 'text', label: 'Topic Category' },
        { name: 'pageSlug', type: 'TEXT', widget: 'text', label: 'Page Slug' },
        { name: 'featured', type: 'BOOLEAN', widget: 'boolean', label: 'Featured', defaultValue: false },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
      ],
    },
    site_navigation: {
      name: 'site_navigation',
      displayName: 'Site Navigation',
      icon: '🧭',
      description: 'Hierarchical navigation menus for headers, dropdowns, and footers',
      schemaVersion: 1,
      fields: [
        { name: 'title', type: 'TEXT', widget: 'text', label: 'Menu Item Label', required: true },
        { name: 'slug', type: 'TEXT', widget: 'slug', label: 'Slug', required: true },
        { name: 'link', type: 'TEXT', widget: 'text', label: 'Target Route URL (e.g. /about, /services)', required: true },
        { name: 'menuKey', type: 'TEXT', widget: 'select', label: 'Menu Key', options: [
          { label: 'Header Main', value: 'header_main' },
          { label: 'Header Dropdown', value: 'header_dropdown' },
          { label: 'Footer Primary', value: 'footer_primary' },
          { label: 'Footer Legal', value: 'footer_legal' },
        ] },
        { name: 'parentSlug', type: 'TEXT', widget: 'text', label: 'Parent Menu Item Slug' },
        { name: 'order', type: 'INTEGER', widget: 'number', label: 'Display Order', defaultValue: 10 },
        { name: 'enabled', type: 'BOOLEAN', widget: 'boolean', label: 'Enabled', defaultValue: true },
      ],
    },
  },
};
